name: auto-approver
run-name: CI for approving PRs

on:
  push:
    branches:
      - "renovate/**"

jobs:
  autoapprove:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: Approve PR
        run: |
          gh pr review --approve || true
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      - name: Enable automerge if required
        if: startsWith(github.ref_name, 'renovate/auto-')
        run: |
          gh pr merge --auto --merge || true
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
