name: On Pull Request

# On pull_request, we:
# * always run tests

on:
  pull_request:

jobs:
  tests:
    name: Run Tests
    uses: ./.github/workflows/tests.yaml

  # TODO: Remove once tested
  publish-bundle:
    name: Publish Bundle
    needs: tests
    uses: ./.github/workflows/publish.yaml
    secrets:
      CHARMCRAFT_CREDENTIALS: ${{ secrets.CHARMCRAFT_CREDENTIALS }}
