name: On Pull Request

# On pull_request, we:
# * always run lint checks
# * always run tests

on:
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

      - name: Install dependencies
        run: python3 -m pip install tox

      - name: Run linters
        run: tox -e lint

  tests:
    name: Run Tests
    needs:
      - lint
    uses: ./.github/workflows/tests.yaml
    secrets: inherit
