name: On Push

# On push to a "special" branch, we:
# * always publish to charmhub at latest/edge/branchname
# * always run tests
# where a "special" branch is one of main or track/**, as
# by convention these branches are the source for a corresponding
# charmhub edge channel.

on:
  push:
    branches:
      - main
      - track/**
      - IAM-240-publish-on-push

jobs:
  tests:
    name: Run Tests
    uses: ./.github/workflows/tests.yaml
    secrets: inherit

  publish-bundle:
    name: Publish Bundle
    needs: tests
    uses: ./.github/workflows/publish.yaml
    secrets:
      CHARMCRAFT_CREDENTIALS: ${{ secrets.CHARMCRAFT_CREDENTIALS }}
