name: Publish and release to latest/edge

on:
  push:
    branches:
      - main
      - track/**
    paths:
      - "bundle.yaml.j2"

jobs:
  publish-bundle-edge:
    name: Publish identity-platform bundle in edge channel
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        bundle: [identity-platform]
    env:
      CHARMCRAFT_AUTH: ${{ secrets.CHARMCRAFT_CREDENTIALS }}
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
      - name: Install dependencies
        run: |
          sudo snap install charmcraft --classic
          sudo apt-get update -yqq
          sudo apt-get install -yqq python3-pip
          sudo --preserve-env=http_proxy,https_proxy,no_proxy pip3 install tox

      - name: Select charmhub channel
        uses: canonical/charming-actions/channel@19db2e9c9da186f64b38b95d8e7e57229f3362da # 2.6.0
        id: select-channel
        if: ${{ inputs.destination_channel == '' }}

      # Combine inputs from different sources to a single canonical value so later steps don't
      # need logic for picking the right one
      - name: Parse and combine inputs
        id: parse-inputs
        run: |
          # destination_channel
          destination_channel="${{ inputs.destination_channel || steps.select-channel.outputs.name }}"
          echo "setting output of destination_channel=$destination_channel"
          echo "::set-output name=destination_channel::$destination_channel"

      - name: Pack and publish bundle
        run: |
          set -ex
          # Use a temporary directory to support publishing any of the bundles in this root dir
          BUILD_DIR=.bundle_build
          mkdir $BUILD_DIR
          CHANNEL=${{ steps.parse-inputs.outputs.destination_channel }}
          # Extract version from the channel, e.g. get 0.1 out of 0.1/edge.
          _CHANNEL=(${CHANNEL//// })
          VERSION=${_CHANNEL[0]} tox -e render-edge
          cp ./bundle-edge.yaml $BUILD_DIR/bundle.yaml
          # Reuse the same charmcraft.yaml, license and readme for all bundles
          cp ./charmcraft.yaml $BUILD_DIR/
          cp ./README.md $BUILD_DIR/
          cp ./LICENSE $BUILD_DIR/
          cd $BUILD_DIR
          charmcraft pack
          charmcraft upload ./*.zip
          export REVISION=$(charmcraft revisions ${{ matrix.bundle }} 2>&1 | awk 'NR==2 {print $1}')
          charmcraft release ${{ matrix.bundle }} --revision $REVISION --channel=${{ steps.parse-inputs.outputs.destination_channel }}
      - name: Dump logs
        if: failure()
        run: |
          printenv | sed 's;=.*;;' | sort
          awk '{print}' /home/runner/.local/state/charmcraft/log/*.log
