name: Publish and release to latest/edge

on:
  workflow_call:
    secrets:
      CHARMCRAFT_CREDENTIALS:
        required: true

jobs:
  publish-bundle-edge:
    name: Publish iam-bundle in edge channel
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        bundle: [iam]
    env:
      CHARMCRAFT_AUTH: ${{ secrets.CHARMCRAFT_CREDENTIALS }}
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo snap install charmcraft --classic --channel=latest/edge
          sudo apt-get update -yqq
          sudo apt-get install -yqq python3-pip
          sudo --preserve-env=http_proxy,https_proxy,no_proxy pip3 install tox
      - name: Pack and publish bundle
        run: |
          set -ex
          # Use a temporary directory to support publishing any of the bundles in this root dir
          BUILD_DIR=.bundle_build
          mkdir $BUILD_DIR
          tox -e render-edge
          cp ./bundle-edge.yaml $BUILD_DIR/bundle.yaml
          # Reuse the same charmcraft.yaml, license and readme for all bundles
          cp ./charmcraft.yaml $BUILD_DIR/
          cp ./README.md $BUILD_DIR/
          cp ./LICENSE $BUILD_DIR/
          cd $BUILD_DIR
          charmcraft pack
          charmcraft upload ./*.zip
          export REVISION=$(charmcraft revisions ${{ matrix.bundle }} 2>&1 | awk 'NR==2 {print $1}')
          charmcraft release ${{ matrix.bundle }} --revision $REVISION --channel=latest/edge
      - name: Dump logs
        if: failure()
        run: |
          printenv | sed 's;=.*;;' | sort
          awk '{print}' /home/runner/snap/charmcraft/common/cache/charmcraft/log/*.log
