name: release

on:
  workflow_dispatch:
  push:
    branches:
    - main
    - "release-**"
    - IAM-877-versioning

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
          target-branch: IAM-877-versioning
