# workflow for checking package versions and opening PRs to bump them
name: Renovate
on:
  workflow_dispatch:
  workflow_call:

jobs:
  renovate:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: List
        run: ls -la

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v38.0.0
        with:
          configurationFile: renovate-config.js
          token: ${{ github.token }}
